### ISSUE TITLE
viewBox is missing from queercat_*.svg files

### ISSUE THREAD

**Issue by moggers87** [ZoeBijl/QueerCats#20]
Some of the queercats have their viewBox attribute missing, which prevents proper scaling:
![screenshot showing the first two queercats not scaling but their heart versions are fine](https://user-images.githubusercontent.com/1490673/60081718-4004fc80-972a-11e9-91c6-2587d7869eb0.png)

I think 1baa3eedb2b643ae35e574752e811d3c1efbc8d9 is to blame - whatever optimiser you were using stripped out viewBox too :crying_cat_face: 

Manually adding `viewBox="0 0 750 750"` fixes the problem.

**Comment by ZoeBijl** [comment]
Thanks for the comment! I’ll see these get added back in.

- [x] Add `viewBox` to all the things
