### ISSUE TITLE
Add flag for male homosexuals

### ISSUE THREAD

**Issue by refacto** [ZoeBijl/QueerCats#21]
Would it be possible to add this proposed flag for male homosexuals?

I sadly only have this png version of the flag, and I'm not yet competent with Inkscape to create an SVG out of it.

![flag](http://boost.biz.tm/flag_mm.png)

**Comment by refacto** [comment]
I now made a (maybe crude) SVG out of it:
[flag_mm.svg](http://boost.biz.tm/flag_mm.svg)

**Comment by ZoeBijl** [comment]
Do you have a suggestion for a shortcode?

**Comment by ZoeBijl** [comment]
Here are previews of the two emoji:

![Cat emoji holding a heart with the male homosexual flag](https://user-images.githubusercontent.com/5457769/74054668-b8c97800-49de-11ea-8f03-d0129541dcac.png)
![Cat emoji with the male homosexual flag as its body](https://user-images.githubusercontent.com/5457769/74054671-bcf59580-49de-11ea-8407-1c4713a62f78.png)

Current shortcaodes are QueerCatHeart_MaleHomosexual and QueerCat_MaleHomosexual. Is there an abbreviation we can use? If not I’d be happy to add them as is 👍.

**Comment by refacto** [comment]
Yay! As a shortcode, I might suggest {QueerCatHeart,QueerCat}MSM, since
[MSM](https://en.wikipedia.org/wiki/Men_who_have_sex_with_men) might be an OK abbreviation, probably not though since that's not sexuality specific

**Comment by ZoeBijl** [comment]
It also seems that MSM is an often used abbrevation for some kind of medicine. I’ll go ahead and merge these in with their longer shortcodes. Instances can adjust the shortcode as they please 👍.

**Comment by refacto** [comment]
OK 👍
