### ISSUE TITLE
Change MLM flag to the better one

### ISSUE THREAD

**Issue by ghost** [ZoeBijl/QueerCats#24]
.

**Comment by Bara-dev** [comment]
To add to the above, the blue MLM flag is often associated with transphobia (as the white bar had no meaning, which in the above one it's for GNC,NB,trans men), which was also adopted by the r/LGBdroptheT subreddit (now deleted) which is also mentioned by the original proposers https://archivalflags.tumblr.com/post/619083546572849152/image-transcription-a-flag-with-seven

**Comment by ZoeBijl** [comment]
I’ll make the change in an upcoming update!

**Comment by ZoeBijl** [comment]
The PNGs and source have been updated. I’ll do the SVGs soon ✨.

**Comment by Bara-dev** [comment]
Thank you so much!!!
